on: [ pull_request ]

jobs:
  test-roadie-tech-insights-action:
    name: Test Roadie Tech Insights Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn build

      - name: Test Roadie Tech Insights on-demand Scorecard API call
        id: test-action-scorecard
        uses: ./
        with:
          catalog-info-path: './catalog-info.yaml'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.ROADIE_ROADIE_API_KEY }}
          scorecard-id: '0159bf78-9211-41c6-9ed6-5ac66b81fb40'